#!/usr/bin/python3

def raise_exception():
    val = 3 / 'a'

    return val
